version: "3.8"

services:
    postgres:
        image: "postgres:latest"
        container_name: "links_postgres"
        restart: unless-stopped
        ports:
            -   "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
